[package]
name = "MUSD stablecoin"
version = "1.0.0"
authors = []

[addresses]
stablecoin = "0x9fc26ce453f4f1e9a7486353830505a32a12c51a59f24734cf8502d94f28a6a8"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]


