[package]
name = "MoveDAO-official"
version = "0.0.2"
authors = []

[addresses]
movedao_addrx = "0x68a5b5caaa956e8f124cd2f01451c73886dc60b88797ba3da254263bd7a4818b"
aptos_framework = "0x1"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

